# Pipeline to deploy The Zoo demo environment

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Biner Azure Cloud Subscription'
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Biner Azure Cloud Subscription'
