# Pipeline to deploy The Zoo demo environment

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.10'
  displayName: 'Install Terraform command line client'
