# Pipeline to deploy The Zoo demo environment

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - terraform-plans/main.tf

stages:
- stage: Validate
  jobs:
  - job: Validate
    continueOnError: false
    steps:
    - task: TerraformTaskV1@0
      displayName: 'Terraform Initialize'
      inputs:
        command: 'init'
        provider: 'azurerm'
        backendServiceArm: 'Biner Azure Cloud Subscription'
        backendAzureRmStorageAccountName: 'thezoostorage'
        backendAzureRmContainerName: 'thezoostoragecontainer'
        backendAzureRmKey: 'foo'
        backendAzureRmResourceGroupName: 'the-zoo-rg'
    - task: TerraformTaskV1@0
      displayName: 'Terraform Validate'
      inputs:
        provider: 'azurerm'
        command: 'validate'

- stage: Deploy
  jobs:
  - deployment: Terraforming
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'Development'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: TerraformTaskV1@0
            displayName: 'Terraform Plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(Pipeline.Workspace)/terraform_out'
              environmentServiceNameAzureRM: 'Biner Azure Cloud Subscription'
          - task: TerraformTaskV1@0
            displayName: 'Terraform Apply'
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(Pipeline.Workspace)/terraform_out'
              environmentServiceNameAzureRM: 'Biner Azure Cloud Subscription'
